spring:
  application:
    name: HRCab
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ***
    url: ***
    username: ***
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: ***
  key: ***